In [1]:
import numpy as np
import tensorflow as tf

In [3]:
"""广播指的是不同形状的数组之间算数运算的执行方式"""

'广播指的是不同形状的数组之间算数运算的执行方式'

In [4]:
"""标量和数组合并时就会发生简单的广播"""

'标量和数组合并时就会发生简单的广播'

In [5]:
arr = np.arange(5)
arr * 4

array([ 0,  4,  8, 12, 16])

In [6]:
"""两个数组之间广播的规则：如果两个数组的后缘维度（即从末尾开始算起的维度）的轴长度相等或其中一方的长度为1
，则认为他们是广播兼容的，广播会在缺失和(或)长度为1的维度上进行"""


'两个数组之间广播的规则：如果两个数组的后缘维度（即从末尾开始算起的维度）的轴长度相等或其中一方的长度为1\n，则认为他们是广播兼容的，广播会在缺失和长度为1的维度上进行'

In [7]:
arr = np.arange(12).reshape(4,3)
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [8]:
arr-arr.mean(0)

array([[-4.5, -4.5, -4.5],
       [-1.5, -1.5, -1.5],
       [ 1.5,  1.5,  1.5],
       [ 4.5,  4.5,  4.5]])

In [9]:
arr - arr.mean(1)

ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

In [10]:
arr-arr.mean(1).reshape((4,1))

array([[-1.,  0.,  1.],
       [-1.,  0.,  1.],
       [-1.,  0.,  1.],
       [-1.,  0.,  1.]])

In [15]:
arr2 = np.arange(24).reshape((2,3,4))
arr3_0 = np.arange(12).reshape((3,4))
print("0轴广播")
print(arr2 - arr3_0)

arr3_1 = np.arange(8).reshape((2,1,4))
print("1轴广播")
print(arr2 - arr3_1)

arr3_2 = np.arange(6).reshape((2,3,1))
print("2轴广播")
print(arr2 - arr3_2)


0轴广播
[[[ 0  0  0  0]
  [ 0  0  0  0]
  [ 0  0  0  0]]

 [[12 12 12 12]
  [12 12 12 12]
  [12 12 12 12]]]
1轴广播
[[[ 0  0  0  0]
  [ 4  4  4  4]
  [ 8  8  8  8]]

 [[ 8  8  8  8]
  [12 12 12 12]
  [16 16 16 16]]]
2轴广播
[[[ 0  1  2  3]
  [ 3  4  5  6]
  [ 6  7  8  9]]

 [[ 9 10 11 12]
  [12 13 14 15]
  [15 16 17 18]]]


In [12]:
arr3 = 

array([[[ 0,  0,  0,  0],
        [ 4,  4,  4,  4],
        [ 8,  8,  8,  8]],

       [[12, 12, 12, 12],
        [16, 16, 16, 16],
        [20, 20, 20, 20]]])

In [13]:
arr2 - np.arange(3).reshape((3,1))

array([[[ 0,  1,  2,  3],
        [ 3,  4,  5,  6],
        [ 6,  7,  8,  9]],

       [[12, 13, 14, 15],
        [15, 16, 17, 18],
        [18, 19, 20, 21]]])

In [14]:
arr2 - np.arange(3)

ValueError: operands could not be broadcast together with shapes (2,3,4) (3,) 

In [17]:
sess = tf.Session()
a = tf.Variable(tf.random_normal((2,3),0,0.1))
sess.run(tf.global_variables_initializer())
sess.run(a)

array([[-0.04280377, -0.12197017, -0.15488295],
       [ 0.12327882, -0.13939475,  0.19996382]], dtype=float32)

In [19]:
b = tf.expand_dims(a,2)
sess.run(b)

array([[[-0.04280377],
        [-0.12197017],
        [-0.15488295]],

       [[ 0.12327882],
        [-0.13939475],
        [ 0.19996382]]], dtype=float32)

In [20]:
sess = tf.Session()
a = tf.Variable(tf.random_normal((2,3),0,0.1))
b = tf.Variable(tf.random_normal((2,1),0,0.1))
c = a - b
sess.run(tf.global_variables_initializer())
sess.run(c)

array([[-0.1419442 ,  0.14135399,  0.22752595],
       [ 0.1382471 ,  0.28228047,  0.13102233]], dtype=float32)

In [21]:
sess = tf.Session()
a = tf.Variable(tf.random_normal((2,3,4),0,0.1))
b = tf.Variable(tf.random_normal((2,1,4),0,0.1))
c = a - b
sess.run(tf.global_variables_initializer())
sess.run(c)

array([[[-0.0154749 , -0.02047186, -0.01022427, -0.08932371],
        [-0.12693939, -0.08069084, -0.15459496,  0.09405404],
        [ 0.09730847,  0.06936138,  0.04050628,  0.15374713]],

       [[-0.02691782, -0.26384184,  0.05825682, -0.07617196],
        [-0.02653179, -0.01997554, -0.06522765,  0.03028341],
        [-0.07577246,  0.03199019,  0.0321    , -0.12571403]]], dtype=float32)

In [22]:
sess = tf.Session()
a = tf.Variable(tf.random_normal((2,3,4),0,0.1))
b = tf.Variable(tf.random_normal((2,4),0,0.1))
c = a - b
sess.run(tf.global_variables_initializer())
sess.run(c)

ValueError: Dimensions must be equal, but are 3 and 2 for 'sub_2' (op: 'Sub') with input shapes: [2,3,4], [2,4].