In [2]:
# 几个numpy函数
import numpy as np

In [42]:
"""
stack函数，原型
numpy.stack(arrays, axis=0)
将一堆数组的数据按照指定的维度进行堆叠。
相当于先增加一维，然后在进行连接
"""
a = np.array([1,2,3])
b = np.array([2,3,4])
np.stack([a,b],axis=0)


array([[1, 2, 3],
       [2, 3, 4]])

In [43]:
np.stack([a,b],axis=1)

array([[1, 2],
       [2, 3],
       [3, 4]])

In [7]:
a = np.array([[1,2,3]])
b = np.array([[2,3,4]])
np.stack([a,b],axis=0)

array([[[1, 2, 3]],

       [[2, 3, 4]]])

In [44]:
a = np.array([1,2,3])
b = np.array([2,3,4])
a = a[np.newaxis,:]
b = b[np.newaxis,:]
np.concatenate([a,b],axis=0)

array([[1, 2, 3],
       [2, 3, 4]])

In [31]:
"""
hstack():函数原型：hstack(tup) ，参数tup可以是元组，列表，或者numpy数组，
返回结果为numpy的数组。
如果进行hstack的数组至少有两维，那么相当于np.concatenate([a,b],axis=1)
"""
a = np.array([1,2,3])
b = np.array([2,3,4])
np.hstack([a,b])

array([1, 2, 3, 2, 3, 4])

In [34]:
# 只有一维的时候，不等价于np.concatenate([a,b],axis=1)，反而等价于np.concatenate([a,b],axis=0)
np.concatenate([a,b],axis=1)

array([1, 2, 3, 2, 3, 4])

In [12]:
np.concatenate([a,b],axis=0)

array([1, 2, 3, 2, 3, 4])

In [17]:
a=[[1],[2],[3]]
b=[[1],[2],[3]]
np.hstack([a,b])

array([[1, 1],
       [2, 2],
       [3, 3]])

In [46]:
a=[[1],[2],[3]]
b=[[1],[2],[3]]
np.concatenate([a,b],axis=1)

array([[1, 1],
       [2, 2],
       [3, 3]])

In [21]:
a = [[[1]],[[2]],[[3]]]
b = [[[2]],[[3]],[[4]]]
np.hstack([a,b])

array([[[1],
        [2]],

       [[2],
        [3]],

       [[3],
        [4]]])

In [22]:
np.concatenate([a,b],axis=1)

array([[[1],
        [2]],

       [[2],
        [3]],

       [[3],
        [4]]])

In [29]:
"""
vstack():函数原型：vstack(tup) ，参数tup可以是元组，列表，或者numpy数组，返回结果为numpy的数组。
如果进行vstack的数组至少有两维，那么相当于np.concatenate([a,b],axis=0)
"""
a = np.array([1,2,3])
b = np.array([2,3,4])
np.vstack([a,b])

array([[1, 2, 3],
       [2, 3, 4]])

In [45]:
# 只有一维的时候 并不等价于np.concatenate([a,b],axis=0)

a = np.array([1,2,3])
b = np.array([2,3,4])
np.concatenate([a,b],axis=0)

array([1, 2, 3, 2, 3, 4])

In [25]:
a=[[1],[2],[3]]
b=[[1],[2],[3]]
np.vstack([a,b])

array([[1],
       [2],
       [3],
       [1],
       [2],
       [3]])

In [26]:
a=[[1],[2],[3]]
b=[[1],[2],[3]]
np.concatenate([a,b],axis=0)

array([[1],
       [2],
       [3],
       [1],
       [2],
       [3]])

In [27]:
a = [[[1]],[[2]],[[3]]]
b = [[[2]],[[3]],[[4]]]
np.vstack([a,b])

array([[[1]],

       [[2]],

       [[3]],

       [[2]],

       [[3]],

       [[4]]])

In [28]:
np.concatenate([a,b],axis=0)

array([[[1]],

       [[2]],

       [[3]],

       [[2]],

       [[3]],

       [[4]]])

In [38]:
import tensorflow as tf
a = tf.convert_to_tensor([1,2,3])
b = tf.convert_to_tensor([2,3,4])

stack_ab = tf.stack([a,b])

a1 = tf.expand_dims(a,axis=0)
b1 = tf.expand_dims(b,axis=0)
concat_ab = tf.concat([a1,b1],axis=0)

with tf.Session() as sess:
    print(sess.run(stack_ab))
    print(sess.run(concat_ab))

[[1 2 3]
 [2 3 4]]
[[1 2 3]
 [2 3 4]]


In [39]:
"""concatenate()函数:
numpy.concatenate((a1, a2, ...), axis=0)
"""
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
np.concatenate((a, b), axis=0)


array([[1, 2],
       [3, 4],
       [5, 6]])

In [40]:
np.concatenate((a, b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [41]:
np.concatenate((a, b), axis=1)

ValueError: all the input array dimensions except for the concatenation axis must match exactly